on:
  push:
    branches:
      - master
    








jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      
      - uses: actions/checkout@v3  
      - name: "login to doker hub"
        run: docker login --username ${{secrets.name}} --password ${{secrets.pass}}
      - name: "building image"
        run: docker build -t ${{secrets.name}}/myapp1 .
      - name: "push image"
        run: docker push ${{secrets.name}}/myapp1